using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;

// Fixes interop assemblies generated by Il2CppInterop on Unity 6 games.
// Bug: some TypeDef rows have nested visibility (NestedPublic etc.) but no
// NestedClass table entry. The CLR then treats them as top-level; several are
// named '<>O' which collide -> BadImageFormatException "Duplicate type with
// name '<>O'" and the whole assembly is rejected.
// Fix: for each orphan row, set visibility to NotPublic (top-level private)
// and point its Namespace at a distinct existing string from the #Strings heap
// so the full name is unique. Tokens are untouched, so all references stay valid.
class Program
{
    static int Main(string[] args)
    {
        var dir = args.FirstOrDefault(a => !a.StartsWith("--"));
        if (dir == null || !Directory.Exists(dir))
        {
            Console.WriteLine(@"usage: dotnet run -- ""<game>\BepInEx\interop"" [--apply]");
            Console.WriteLine("       without --apply it only reports the offending files and rows.");
            return 1;
        }
        var apply = args.Contains("--apply");
        int filesPatched = 0, rowsPatched = 0;

        foreach (var file in Directory.GetFiles(dir, "*.dll"))
        {
            try
            {
                var patched = FixFile(file, apply, out int rows);
                if (rows > 0)
                {
                    Console.WriteLine($"{Path.GetFileName(file)}: {rows} orphan nested typedef(s){(apply ? " PATCHED" : "")}");
                    rowsPatched += rows;
                    if (patched) filesPatched++;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"{Path.GetFileName(file)}: ERROR {ex.Message}");
            }
        }

        Console.WriteLine($"Done. files patched: {filesPatched}, rows patched: {rowsPatched}");
        return 0;
    }

    static bool FixFile(string file, bool apply, out int orphanCount)
    {
        orphanCount = 0;
        byte[] bytes = File.ReadAllBytes(file);

        using var ms = new MemoryStream(bytes, writable: false);
        using var pe = new PEReader(ms);
        var md = pe.GetMetadataReader();

        // find orphan rows: nested visibility but nil declaring type
        var orphans = new List<(int Row, TypeDefinition Td)>();
        foreach (var h in md.TypeDefinitions)
        {
            var td = md.GetTypeDefinition(h);
            var vis = td.Attributes & System.Reflection.TypeAttributes.VisibilityMask;
            bool nestedVis = vis != System.Reflection.TypeAttributes.NotPublic &&
                             vis != System.Reflection.TypeAttributes.Public;
            if (nestedVis && td.GetDeclaringType().IsNil)
                orphans.Add((MetadataTokens.GetRowNumber(h), td));
        }
        orphanCount = orphans.Count;
        if (orphans.Count == 0 || !apply) return false;

        // existing full names (top-level view: namespace + name)
        var existingFullNames = new HashSet<string>();
        foreach (var h in md.TypeDefinitions)
        {
            var td = md.GetTypeDefinition(h);
            if (td.GetDeclaringType().IsNil)
                existingFullNames.Add(md.GetString(td.Namespace) + "." + md.GetString(td.Name));
        }

        // pool of distinct existing namespace strings (heap offset + text)
        var nsPool = new List<(int Offset, string Text)>();
        var seenNs = new HashSet<int>();
        foreach (var h in md.TypeDefinitions)
        {
            var td = md.GetTypeDefinition(h);
            if (td.Namespace.IsNil) continue;
            int off = md.GetHeapOffset(td.Namespace);
            if (off != 0 && seenNs.Add(off))
                nsPool.Add((off, md.GetString(td.Namespace)));
        }

        // metadata layout
        int metadataFileOffset = pe.PEHeaders.MetadataStartOffset;
        int typeDefTableOffset = md.GetTableMetadataOffset(TableIndex.TypeDef);
        int rowSize = md.GetTableRowSize(TableIndex.TypeDef);
        int strIdxSize = md.GetHeapSize(HeapIndex.String) > 0xFFFF ? 4 : 2;

        int poolIdx = 0;
        foreach (var (row, td) in orphans)
        {
            string name = md.GetString(td.Name);

            // pick a namespace making the fullname unique
            int nsOffset = -1; string nsText = null;
            while (poolIdx < nsPool.Count)
            {
                var cand = nsPool[poolIdx++];
                if (!existingFullNames.Contains(cand.Text + "." + name))
                {
                    nsOffset = cand.Offset; nsText = cand.Text;
                    break;
                }
            }
            if (nsOffset < 0) throw new Exception("namespace pool exhausted");
            existingFullNames.Add(nsText + "." + name);

            int rowFileOffset = metadataFileOffset + typeDefTableOffset + (row - 1) * rowSize;

            // Flags: uint32 at +0 -> clear visibility bits (mask 0x7) => NotPublic
            uint flags = BitConverter.ToUInt32(bytes, rowFileOffset);
            uint newFlags = flags & ~0x7u;
            BitConverter.GetBytes(newFlags).CopyTo(bytes, rowFileOffset);

            // Namespace index at +4 + strIdxSize (after Name)
            int nsFieldOffset = rowFileOffset + 4 + strIdxSize;
            if (strIdxSize == 2)
            {
                if (nsOffset > 0xFFFF) throw new Exception("ns offset too large for 2-byte index");
                BitConverter.GetBytes((ushort)nsOffset).CopyTo(bytes, nsFieldOffset);
            }
            else
            {
                BitConverter.GetBytes(nsOffset).CopyTo(bytes, nsFieldOffset);
            }

            Console.WriteLine($"    row {row}: '{name}' -> namespace '{nsText}', vis NotPublic");
        }

        File.WriteAllBytes(file, bytes);
        return true;
    }
}
